### ISSUE TITLE
Automatic FNMT personal certificate issuer via DNIe

### ISSUE THREAD

**Issue by brainstorm** [rickyepoderi/dnie-pkcs11-tester#2]
This is just a thought/idea I had while poking aroud this small piece of software, let me know what you think about that...

Every time I had to interact with my DNIe, it has been an annoying and frustrating experience, to say the least. I know that the whole point of having a piece of hardware, a smartcard reader, helps in securing our private keys... but at some point it becomes more of a hassle than a convenience.

On top of that, the recent [ROCA vulnerability](https://twitter.com/marcan42/status/928491296003469313) makes me even more annoyed and skeptical on using this piece of tech that has never lived up to its potential and general public expectations on usability, IMHO.

Have you ever thought about having a flag in this pkcs11 tester (or another related project of yours that links to this lib) which automatically connects to the reader and then to this FNMT service:

https://www.sede.fnmt.gob.es/certificados/persona-fisica/obtener-certificado-con-dnie

And automatically generates a `.p12` (PKCS12 blob) for the user, all in one single command/interaction? (obviously with the obligatory PIN prompt, but not more than 2 steps?).

That would be really easily installable in pretty much any browser and other devices, with minimal UX friction. I know, it comes with "reduced" security, but still, personally that's a price I'm very much willing to pay, I can secure my keys in many other ways.

Would you base such a "util"/"helper" program with this library or do you think about something else you are more used to?

**Comment by rickyepoderi** [comment]
Hi,

Sorry but I'm not interested in doing such a program. There are two main reasons:

1. I don't use the FNMT certificate. I just use the DNIe to access some governmental sites from time to time, I have never used the signature key for something real (just my tests).
2. I don't know how the process to get the FNMT certificate is and I don't want to know it. I suppose that using a PKCS#11 library is just adding it to firefox and access some FNMT page, but this is a problem of the FNMT, not mine. Besides this kind of scripts/programs depend completely on what the other party provides, if FNMT changes something the script doesn't work. I think you have to ask about this to the FNMT itself.

In general the ROCA vulnerability is a problem in the chip that some DNIe 3.0 cards use. So it's not a problem directly caused by the DGP or other Spanish authority. What is true is that the way it's being managed is a mess and the lack of information is worrisome. If I understood the vulnerability correctly, they just need to re-generate the certificates (RSA keys) not using the fast method (affected by the issue) but the common/slow one. So I suppose that some day the software inside the machines that manage the DNIe in the police stations will be updated and they will be able to re-generate the certificates (now they seem to be revoked) in the affected cards. Nevertheless, knowing them, this can be a long process. I re-newed my DNIe to have a 3.0 version last year and in theory I'm affected by the vulnerability, but I don't use it very often, so I don't really care.

The FNMT certificate is a software PKCS#12 file that has the key pair and the certificate. So the DNIe is much more secure (the private key cannot even go out the card). Sadly the ROCA vulnerability changed that part for the affected ID cards.

**Comment by rickyepoderi** [comment]
Closing this cos it's really not related to this project.
